### DISCUSSION TITLE
Réorganisation de l'espace de nom dirigeant / indépendant

### DISCUSSION THREAD

**Discussion by lajarre** [betagouv/mon-entreprise#2644] [Idées]
Je n'arrive pas à comprendre quelle est la différence entre les termes "TNS" et "indépendant". Il est clair cependant qu'on parle d'un régime ou statut _social_.

Dans les règles on semble utiliser "indépendant" pour ce que d'autres appellent TNS.

Notre règle sur la question est:

```yaml
dirigeant:
  question: Quel est le régime social du dirigeant ?
  par défaut: non
  formule:
    une possibilité:
      choix obligatoire: oui
      possibilités:
        - auto-entrepreneur
        - assimilé salarié
        - indépendant
```

Tout d'abord pouvez-vous m'éclairer sur ce qu'on entend exactement par "indépendant"? Y a-t-il une définition officielle?  
Note: ce terme apparaît bien dans la loi, mais je n'ai pas trouvé de glossaire sur Legifrance ou autre.

Si ce terme est utilisé de manière interchangeable avec TNS, alors il me semble que TNS est un terme plus explicite donc préférable.

cc @johangirod @mquandalle
