### DISCUSSION TITLE
Intégration des frais professionnels dans la rémunération

### DISCUSSION THREAD

**Discussion by liliced** [betagouv/mon-entreprise#3125] [General]
### Point socio-légal : 

Le remboursement des frais professionnels est en principe **exonéré de cotisations sociales et d'impôt**, selon la logique qu'il s'agit de frais engagés par le salarié pour travailler, et qu'il ne devraient pas lui "coûter" encore plus cher. Lorsque le remboursement s'effectue sur frais réels (avec factures et justificatifs), il est entièrement exonéré.

Cependant, lorsque le remboursement s'effectue au forfait, une partie peut être soumise à cotisation et impôt. C'est le cas lorsque le montant dépasse le plafond d'exonération.

Il y a donc déjà une subtilité : **dans certains cas, une part du remboursement de frais professionnels doit être soumise à cotisations et imposition**, mais dans la plupart des cas non.

> Source : https://www.urssaf.fr/accueil/employeur/beneficier-exonerations/frais-professionnels.html

### Contexte de mon-entreprise :

Le modèle social ne gère que 2 types de frais professionnels : les titres-restaurant et les **trajets domicile-travail** (transports publics, prime de transport et/ou forfait mobilités durables).

Pour le simulateur salarié, on ne se base que sur les remboursement avec allocation forfaitaire. Ce qui soulève déjà 2 points :
- **On ne précise pas clairement à l'utilisateurice** qu'il ne s'agit pas de remboursements sur frais réels (la documentation explique les primes forfaitaires sur lesquelles on pose des questions mais l'interface du simulateur ne l'indique pas).
- **Il peut y avoir des sommes soumises à cotisations** (et ce n'est pas non plus indiqué)

### Calculs

Actuellement les frais professionnels sont intégrés au calcul de la rémunération du salarié de la façon suivante : 

- **Rémunération brute :** inclus

```
salarié . rémunération . brut:
  somme:
    - contrat . salaire brut
    - avantages en nature . montant
    - primes
    - indemnités CDD
    - heures supplémentaires
    - heures complémentaires
    - frais professionnels

  abattement: activité partielle . retrait absence
```

- **Assiette des cotisations sociales :** exclu

```
salarié . cotisations . assiette:
  somme:
    - sans prévoyance
    - prévoyances . employeur . non déductible socialement
  avec:
    sans prévoyance:
      valeur: rémunération . brut
      abattement:
        somme:
          - rémunération . frais professionnels . déductible
          - contrat . stage . gratification minimale
```

- **Net imposable :** exclu

```
salarié . rémunération . net . imposable:
  valeur: sans déductions
  abattement:
    somme:
      - frais professionnels . déductible
      - exonération prime d'impatriation
      - exonération stagiaires et apprentis
      - heures supplémentaires et complémentaires défiscalisées
```

- **Net à payer avant impôt :** soustraction du montant des titres-restaurants (ce qui revient au total à n'avoir ajouté que la part employeur)

```
salarié . rémunération . net . à payer avant impôt:
  somme:
    - net
    - (- avantages en nature . montant)
    - (- frais professionnels . titres-restaurant . montant)
```

Les montants "importants" (cotisations, net imposable, net à payer) sont corrects. Cependant **la rémunération brute ne devrait pas inclure les frais professionnels**.

![image](https://github.com/user-attachments/assets/3f067179-eada-4fae-91a6-cba543597924)

> Source : https://www.service-public.fr/particuliers/vosdroits/F2408

C'est d'autant plus problématique lorsqu'on regarde la fiche de paie.

### Fiche de paie

Il est difficile de trouver une source fiable, claire et exhaustive sur la présentation de la fiche de paie mais d'après le tableau ci-dessus et [Légifrance](https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000049854119), le remboursement des frais professionels devraient être : 
- exclu de la partie "Salaire brut"
- inclus dans la partie "Salaire net"

Actuellement, ils ont une ligne dédiée dans la partie "Salaire brut" et avec [la nouvelle présentation de la fiche de paie](https://3091--mon-entreprise.netlify.app/simulateurs/salaire-brut-net?salaire-brut=2600%E2%82%AC%2Fmois&salari%C3%A9+.+r%C3%A9mun%C3%A9ration+.+frais+professionnels+.+trajets+domicile+travail+.+transports+publics+.+montant=100%E2%82%AC%2Fmois&salari%C3%A9+.+r%C3%A9mun%C3%A9ration+.+frais+professionnels+.+trajets+domicile+travail+.+transports+publics+.+taux+employeur=100%25&unite=%E2%82%AC%2Fmois), ils en ont aussi une dans la partie "Salaire net".

### Cas général

Dans le cas où les remboursements sont totalement exonérés c'est simple, il faut : 
- supprimer `frais professionnels` de la rémunération brute
- supprimer la ligne frais professionnels dans "Salaire brut"
- ajouter `frais professionnels . trajets domicile-travail . employeur` au net à payer avant impôt
- afficher le total de ces remboursements sur des lignes dédiées dans "Salaire net"

### Cas particulier

Cela se complique si les montants dépassent les plafonds d'exonération.

En effet, puisque l'excédent doit être soumis à cotisations, il semble logique de **l'inclure à la rémunération brute**. Sans cela, on aurait des cotisations basées sur un élément placé plus bas dans la fiche de paie, alors qu'on s'attend à pouvoir la lire linéairement de haut en bas.

Mais, même si c'est peut-être le plus juste d'un point de vue comptable, il serait étrange de **découper ces sommes en 2 et d'en placer une dans "Salaire brut" et l'autre dans "Salaire net"**.
Par exemple pour un abonnement à 100 €/mois, remboursé à 100% on aurait 25 € dans la section "Salaire brut" et 75 € dans la section "Salaire net" alors qu'on s'attendrait à retrouver une seule ligne à 100 €, ou au moins les 2 lignes côte à côte.

Maintenant la question à 1 million :  **qu'en pensez-vous ?**
