### ISSUE TITLE
Formalisation du système de type de publicodes 

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1126]
Je propose d'élargir ici la discussion entamé dans #963, et de réfléchir aux types dans le langage publicodes.

Cette discussion est un préliminaire à une meilleure intégration des types dans publicodes : il s'agit d'établir une formalisation idéale minimale du système de type de publicodes afin d'en fiabiliser l'implémentation, tout en aboutissant au moins de modifications des programmes existants possible.

## Le système de type de publicodes

Le système de type de publicode côté utilisateur est relativement simple. Il comporte les types suivants :

- Booléen
- Texte
- Date
- Nombre
- Objet externe
- Option
- Possibilités

#### Nombre
```
type nombre = { valeur: number; unité: unit }
```

Le type nombre définit également une unité. Celle-ci peut être vide, dans ce cas, le nombre est considéré un rapport (par exemple un taux).

Lorsqu'un nombre peut être converti d'une unité vers d'autres, alors ces unités forment une classe d'équivalence. Par exemple `année`, `mois`, `jour` et `semaine`. Ou `kg`, `g`, `mg`, `lb` et `oz`. 

Par conséquent, on peut substituer type de nombre unité par un autre type d'unité de même classe. Par exemple : `€/mois` et `€/an`. La conversion est effectuée à l'évaluation.

Cela abouti aux effets suivants : 
- `3 €/mois + 154 €/an` est une formule valide
- `3 €/mois + 154 %` est une formule invalide

#### Option et Possibilités
Option est un type littéral définit globalement. On peut en construire une instance via le symbole '#'

Dans l'exemple ci dessous:
```yaml
CDD: 
	formule: #CDD
```
CDD est de type #CDD

Le constructeur de type Possibilités permet de définir une union d'Option.
```yaml
contrat: 
  type:
    une possibilité parmis: 
	  - CDD
	  - CDI
	  - Stage
```
Le type de contrat sera: `#CDD | #CDI | #Stage`

Il est possible de tester l'égalité d'options : 
```contrat = #CDD```

On peut ne peut remplacer une règle de type possibilité seulement par une union plus restreinte (sous-type)
```yaml
assimilé salarié . contrat: 
  type: option
  remplace: 
    - règle: contrat
	  par: #CDI
```

On peut imaginer l'ajout d'un mécanisme `correspondance` qui vérifie la complétude des options listées (comme évoqué dans https://github.com/betagouv/mon-entreprise/pull/824#issuecomment-573446347).

#### Objet externe
Le type `Objet externe` est un type permettant de manipuler dans publicodes des objets javascript, généralement issus d'API externes. Le seul mécanisme qui permet de manipuler une variable de ce type est `synchronisation`.

Par exemple, le cas de l'API commune peut être traité ainsi : 
```
localisation . commune:
  type: objet externe
  affichage:
    champs spécial: commune

localisation . département:
  synchronisation: 
    règle: commune
	chemin: departement . nom
	type: 
	  une possibilité parmi:
        - Ain
        - Aisne
        - Allier
        - Alpes-de-Haute-Provence
        - Hautes-Alpes
        - Alpes-Maritimes
        - Ardèche
          ...
        - Guadeloupe
        - Martinique
        - Guyane
        - La Réunion
        - Mayotte
		
localisation . département:
  synchronisation: 
    règle: commune
	chemin: departement . nom
	type: 
	  une possibilité parmi:
        - Ain
        - Aisne
        - Allier
        - Alpes-de-Haute-Provence
        - Hautes-Alpes
        - Alpes-Maritimes
        - Ardèche
          ...
        - Guadeloupe
        - Martinique
        - Guyane
        - La Réunion
        - Mayotte

localisation . versement transport:
  synchronisation: 
    règle: commune
	chemin: taux versement transport
	unité: ''
```

Le cas d'usage est la mise à jour de plusieurs variables à partir de la réponse à une seule question. 

C'est la seule potentielle faiblesse du système de type, on l'utilisateur est attendu de fournir un objet javascript de la bonne forme dans la situation, sans vérification formelle de la part du moteur.

### Type internes

Par ailleurs, publicodes possède un certains nombre de type interne utile pour définir son modèle d'évaluation et pour l'inférence de type des mécanismes : 

- **`Non Applicable`** : la valeur est non applicable dans le cadre de la situation présente. Cela correspond conceptuellement au fait qu'elle est non définie (par exemple, le type d'activité libérale règlementée n'est pas applicable dans le cas d'une entreprise d'artisanat), ou qu'elle ne s'applique pas (par exemple, la cotisation CURPS ne s'applique pas pour les revenus professionnels négatifs)

- **`Manquant`** : il est impossible de connaître la valeur de cette variable. Par exemple, si elle n'a ni formule, ni valeur par défaut et pas de valeur dans la situation. Ou alors elle possède une formule mais une des composante est manquante.

- **`Temporelle T`** : type une variable dont la valeur change au cours du temps. C'est un foncteur applicatif.

Toute formule de règle possède un type qui peut être inféré par le moteur. En outre, la règle possède un champs "type" permettant de vérifier le type de sa formule, ou de définir son type dans le cas de variable "feuille" (définie par l'utilisateur dans la situation).

```
Formule = Booléen | Nombre | Texte | Date | Spécial | Possibilités
```

Le type Valeur, correspondant à l'évaluation d'une règle de type T est le suivant :
```
Valeur T = Non Applicable | Manquante | T
```

#### Temporelle T
Le type temporelle permet de representer une variable dont la valeur change au cours du temps. Il ne peut pas être explicitement définit par l'utilisateur au niveau de la règle. Le moteur s'occupe de 'lifter' automatiquement les mécanismes opérant sur le type T pour qu'ils opèrent sur Temporelle T. Au vu de l'utilisateur, le fait qu'une règle soit une variable ou variable temporelle est donc tout à fait transparent. 

Par conséquent, le type temporel d'une règle n'est pas determinable statiquement. Chaque noeud peut donc être de type `T | Temporelle (T)`, de manière indifférenciée. Seule l'execution du programme aboutit à l'une ou l'autre des valeurs.

Temporelle est un foncteur applicatif. 

### Fonctionalités limités
Contrairement à la plupart des langages de programmation, publicodes n'a pas les fonctionalités suivantes :
- L'utilisateur ne peut pas manipuler de type fonction : les mécanismes sont définis une fois pour toute dans la structure du langage même.
- L'utilisateur ne peut pas manipuler d'unions de type (outre Possibilité).
- L'utilisateur ne peut pas manipuler de type "record".
- L'utilisateur ne peut pas manipuler d'intersections de type.

Au vu de la faible complexité de son système de type, Publicodes devrait pouvoir être un langage statiquement typé.

### Type des mécanisme
On peut donc définir une inférence de type pour chaque mécanisme, ainsi que les types pour lesquelles ils sont définit.
#### a x b
Par exemple, pour la multiplication, on a les règles suivante : 
```
(a: Non Applicable, b:*) => Manquante
(a: Manquante, b:*) => Manquante
(a: Nombre u, b:Nombre v) => Nombre (u.v)
(a: Temporelle (T), b: U) => Temporelle (T x U)
(a: T, b: U) => U x T
```
Définit sur l'espace `(Evaluation(Nombre), Evaluation(Nombre))`

#### somme
Pour le mecanisme somme, on a : 
```
(a: Valeur(T)[]) => Valeur(T)[]
```
Definit sur `Evaluation(Nombre)[]`

## Questions ouvertes

- Quel solution d'implémentation pour la verification de type dans publicodes ? 
- Comment la question des unités est-elle soluble dans un système de type standard ? Ou doit-elle être approchée séparément ? Le type doit-il être le même pour une classe d'unité ? Mais alors comment définir la notion de conversion ?
