### ISSUE TITLE
Meilleur gestion du taux non applicable dans un produit / un allègement, 

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1151]
```yaml
cotiz:
  formule:
    produit:
       assiette: 1000 €
       taux: taux
taux:
  applicable si: non
```
Produit devrait valoir 1000€, et non 'false'

A voir avec la refacto de l'applicabilité #1090
