### ISSUE TITLE
Fusion mécanisme/ruleProp

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1153]
Je pense qu'il serait temps de réécrire et formaliser la façon dont l'applicabilité est gérée aujourd'hui dans le moteur. 

Dans #1126, je proposais de théoriser l'applicabilité comme un type de base du langage, chaque valeur pouvant être applicable (et avoir un type) ou non applicable.

Je pense qu'il est temps d'introduire cette notion dans implémentation.

Par ailleurs, l'applicabilité ne devrait pas être différent des autres mécanisme, et devrait donc pouvoir être utilisée à l'intérieur des formules. 

```yaml
prix: 
   formule:
      produit: 
        assiette: 100 €
        taux: 
          valeur: 50%
          applicable si: réduction
```
On s'apercoit ici qu'il n'y a pas de raison d'avoir applicable / non applicable directement dans la règle. A part pour simplifier la lisibilité...

Et je viens de me rendre compte d'un truc assez puissant. Tous les attributs de la règle influant sur le calcul devrait pouvoir être utilisés à l'intérieur d'une formule.

```yaml
prix: 
   description: le prix à facturer
   formule:
      produit: 
        assiette: achat          
        taux: 
          valeur: taux magasin
          par défaut: 50%
          applicable si: réduction
       unité: € 
       arrondi: 2 unités
```
`par défaut`, `unité` sont des mécanismes. 
`par défaut` permet d'affecter une valeur à une variable 'manquante'
`unité` permet de faire du casting et de la vérification de type statique

Et inversement. Une règle n'est qu'un mécanisme avec tout un tas de méta dedans. Si on dit que `formule` et `valeur` sont équivalents, on peut imaginer écrire directement :

```yaml
prix: 
   description: le prix à facturer
   unité: € 
   arrondi: 2 unités
   formule:
      produit: 
        assiette: achat          
        taux: 
           valeur: taux magasin
           par défaut: 50%
           applicable si: réduction
```

Et même : 
```yaml
prix: 
   description: le prix à facturer
   unité: € 
   arrondi: 2 unités
   produit: 
      assiette: achat
      taux: 
         valeur: taux magasin
         par défaut: 50%
         applicable si: réduction
```

Cela veut dire que la règle n'a pas de parsing particulier. C'est juste un mécanisme comme un autre à parser. Il n'y a plus de différence entre formule et règle. 

M'est avis que cela va simplifier drastiquement parseRule
Bref je suis super chaud pour faire cette refacto très rapidement.
