### ISSUE TITLE
Documentation : variables manquantes quand on clique sur "Lancer le calcul"

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1157]
La documentation permet de voir le code source publicode de la règle courante, et de l'ouvrir dans le Publicode Studio pour la modifier. Malheureusement l'import ne fonctionne quasiment jamais car la règle en référence d'autres qui ne sont pas importées. exemple :

```yaml
impôt:
  icônes: 🏛️
  unité: €/an
  description: Cet ensemble de formules est un modèle ultra-simplifié de l'impôt
    sur le revenu, qui ne prend en compte que l'abattement 10%, le barème et la
    décôte.
  titre: impôts sur le revenu
  formule:
    somme:
      - produit:
          assiette: revenu imposable [€/an]
          taux: taux d'imposition
      - dirigeant . auto-entrepreneur . impôt . versement libératoire . montant
        [€/an]
    arrondi: oui
```

la règle `impôt` référence `impôt . revenu imposable`, `impôt . taux d'imposition`, et `dirigeant . auto-entrepreneur . impôt . versement libératoire . montant`.

Pour réparer l'import dans le studio, l'idée serait de récupérer cette liste de dépendances (nécessite l'implémentation de #986) et pour chacune d'elle récupérer la valeur dans la situation courante, que l'on ajoute en tête de l'import :

```yaml
impôt . revenu imposable: 2300 €/mois
impôt . taux d'imposition: 4%
dirigeant . auto-entrepreneur . impôt . versement libératoire . montant: non

impôt:
  [...]
```
