### ISSUE TITLE
Transitivité du remplacement

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1296]
Maintenant que #1139 est implémenté, il nous faut nous pencher sur la transitivité du remplacement. Je copie pour rappel les passages interessants discuté dans l'issue ci-dessus : 

### Transitivité

Je remet ici le cas d'usage pour comprendre de quoi il en retourne :

```yaml
assiette des cotisations:

déduction forfaitaire:
  remplace: 
    règle: assiette des cotisations 
  formule: assiette des cotisations * 50%
  
déduction forfaitaire exception chômage des journalistes:
  remplace:
    règle: déduction forfaitaire
    dans: chômage
    par: non applicable
```
(on peut imaginer d'utiliser le mécanisme rends non applicable plus facile à lire, et qui est du sucre syntaxique pour remplace par non applicable).

Comme on le voit, le cas d'usage est très largement justifié. Il faut donc "le faire marcher" et trouver comment l'insérer dans notre définition.

Pour moi, cela peut être réglé en continuant à transformer la formule tant qu'il existe des remplacements applicables.
```
Remplacements, Règles
RemplacementsAppliqués = []
Tant qu'il existe un RemplacementApplicable dans Remplacements:
  Règle = AppliqueRemplacement(RemplacementApplicable, Règle)
```
Mais la on tombe potentiellement sur un os : que se passe-t'il en cas de cycle de remplacement applicable ?

```yaml
a: 0
b: a
y:
  remplace: a
  par: a + 1
```
ou encore :
```yaml
a: 0
b: 1
c: a + b
y:
  - remplace: b
    par: a + 1
  - remplace: a
    par: b
  dans: c
```

Dans b, on peut continuer à appliquer indéfiniement le remplacement définit dans y. On retombe sur notre problème de détection de cycle. Tout ça pour ça ? Oui... et non. Car c'est un problème qu'on peut maintenant résoudre facilement car il s'agit uniquement de cycle dans la définition des remplacement (et non une combinaison remplacement / formule). Il faut de construire un graphe des remplacements définis sur la règle (pour chaque règle), et ça devrait le faire.

### Implémentation
Pour résumer, il faut ajouter une logique de remplacement dans les remplacements, règles par règle. Il faut en outre faire une vérification pour les cycles possibles à l'interieur du remplacement.
