### ISSUE TITLE
Bug missingVariables ? 

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#1316]
Dans ce cas d'utilisation simple, https://bit.ly/3gQOzaP, en ajoutant la ligne `console.log(rule.dottedName, rule.missingVariables)` au fichier RulePage.tsx, j'observe que les missingVariables de la variable "transport . avion" incluent des questions qui n'ont aucune utilité.

```yaml
transport:
  description: |
    ![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Correspondances_Pey_Berland_août_2016.jpg/640px-Correspondances_Pey_Berland_août_2016.jpg)
    
    Sans surprise, le transport et avant tout le transport basé sur le pétrole constitue une part très importante de notre empreinte.
  icônes: 🚦
  somme: 
    - voiture
    - avion

transport . voiture:
  formule: empreinte * km

transport . voiture . empreinte: 0.12
transport . voiture . km: 
  question: COMBIENKM
  par défaut: 1000

transport . avion:
  applicable si: usager
  formule: empreinte * km

transport . avion . km: 
  question: COMBIENKM
  par défaut: 10000

transport . avion . empreinte: 0.300

transport . avion . usager:
  question: Prenez-vous l'avion ?
  par défaut: oui

```

 ```js
 {
"transport . avion . km": 24.005,
"transport . avion . usager": 24.007099999999994,
"transport . voiture . km": 8.0016}
```

Ce bout de code est une version simple de mon fichier [transport.yaml](https://github.com/betagouv/ecolab-data/blob/gros-merge/data/transport.yaml) dans ma grosse mise à jour pour utiliser la lib.

Est-ce qu'il y a quelque chose d'ancien dans mon yaml qui fait planter le calcul des missingVariables (d'où mon exemple simplifié pour reproduire et comprendre), ou est-ce que c'est un bug de l'algo pas testé et pas vu dans mon-entreprise car vous ne produisez que des simulateurs assez généraux (équivalent de transport ici plutôt que transport . avion) ?
