### ISSUE TITLE
Ajouter une logique à Publicodes pour éviter les erreurs d'assiette

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1469]
Du fait de la complexité social/fiscal et des différents dispositifs d'exonérations, on a une vraie difficulté à écrire et relire les règles Publicodes pour la définition des assiettes, et à s'assurer qu'elles sont correctes. Voir par exemple #942.

J'ai l'intuition que l'on pourrait encoder une contrainte de "non comptage en double" dans Publicodes pour s'assurer de la cohérence des règles.

La compta en partie double est par exemple un système s'assurant que l'on oublie pas d'intégrer un élément, ni que l'on en compte un en double. C'est cependant une idée assez difficile à reproduire dans le cadre de publicodes, et pour être honnête l'écriture sous forme de débit / crédit n'est pas la chose la plus intuitive qui soit. Mais peut-être que résonner en flux (rémunération du dirigeant = de l'argent en moins pour l'entreprise et de l'argent en plus pour pour le foyer fiscal, le tout étant à l'équilibre) pourrait nous aider. On n'aurait pas besoin d'ajouter un montant d'un côté et de le retirer de l'autre mais on ferait les deux à la fois.

Une autre possibilité serait d'avoir un système de composantes type "imposable / pas imposable" et d'avoir une vérification statique qui s'assure que l'on additionne jamais 2 fois « la même chose » dans une règle. Par exemple :

```yaml
a: imposable: 10, pas imposable: 5
b: 20 + a . imposable

assiette cotis: b + a . pas imposable # ✅ Type Check

assiette impôt: b + a . imposable # ❌Type Check : `a . imposable` compté 2 fois
```

Tout ça est assez vague dans mon esprit, mais il y a sans doute des contraintes à valider statiquement sur notre base de règles existante.
