### ISSUE TITLE
Ajouter un mécanisme `si dans la situation`

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1524]
Le problème à résoudre est le suivant :

```yaml
a: b *  2
b: a / 2
```
On a écrit ici les équations dans les deux sens pour éviter d'appeler le mécanisme `inversion numérique`. Cependant, si la situation est vide, on abouti à un cycle. Pour éviter cela, l'idée est de spécifier qu'une des formule s'applique uniquement dans le cas où le paramètre est spécifié dans la situation : 

```yaml:
a: b * 2
b:

**Comment by denismerigoux** [comment]
Hum je suis pas très familier avec la littérature sur les langages à calculs inversibles ou partiellement inversibles (j'ai vu passer un papier sur ça récemment https://dl.acm.org/doi/pdf/10.1145/3409000) mais dans ce cas précis il me semble que vous gagneriez à avoir une syntaxe spéciale pour déclarer deux variables reliées par des fonctions inverses non ?

```
a <-> b : 
  - a : b * 2
  - b : a * 50%
```

Après il faudrait gérer ça de manière spéciale dans votre moteur d'exécution, ça revient à avoir une arrête à double sens dans votre graphe de dépendance, et donc de la traiter de manière spéciale puisque pour calculer `a` on a pas besoin de `b`, ni vice-versa.

**Comment by mquandalle** [comment]
La notion de "situation" n'existe pas au niveau du langage, c'est seulement dans les simulateurs que l'on définit une "situation" comme un ensemble de remplacements. Comme Denis, il me semble préférable de parler « d'inversion » de la formule, même si c'est une implémentation différente du mécanisme d'inversion par dichotomie que nous utilisons par ailleurs.

À terme ces formules d'inversions pourraient certainement être inférées (cf. POC #568), mais donner les formules dans les deux sens est une bonne solution en attendant. Pour éviter des erreurs d'incohérence (une formule mise à jour mais pas son inverse par exemple), je pense aussi que les deux formules doivent être définies au même endroit dans le code (et non dans deux règles différentes).

```yaml
chiffre d'affaires:
  description: Montant total des recettes brutes
  formule: revenu net + cotisations
  inversible avec:
    revenu net: chiffre d'affaires - cotisations
    cotisations: chiffre d'affaires - revenu net
```
