### ISSUE TITLE
exonérations . ZFU toujours à 0?

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1749]
Il me semble qu'il y a un non-sens dans la règle `dirigeant . indépendant . cotisations et contributions . exonérations . ZFU`, je pense que le plafond avec recalcul rend `null` (cf. la limite imposée sur le recalcul imbriqué) et donc, en tant que telle, la règle est toujours à 0. A vérifier plus en détail.

```yaml
dirigeant . indépendant . cotisations et contributions . exonérations . ZFU:
  applicable si: établissement . ZFU
  produit:
    assiette: maladie
    taux: taux
    # TODO : Le plafond est proratisé en début / fin d'exonération
    plafond:
      recalcul:
        avec:
          revenu professionnel: 3042 heures/an * SMIC horaire
  arrondi: oui
  unité: €/an
```
