### ISSUE TITLE
[salarié] Calcul du plafond de la sécurité sociale erroné

### ISSUE THREAD

**Issue by fmata** [betagouv/mon-entreprise#2049]
Bonjour,

J'ai posté initialement sur betagouv/publicodes#177 mais sa place est plus ici, désolé.

Le calcul du plafond de la sécurité sociale qui est fait dans la règle `contrat salarié . plafond sécurité sociale` nous semble faux depuis 2017 où les URSSAF demandent à ce que les absences non rémunérées soient prises en compte en jours calendaires au lieu d'être en heures.

> valeur mensuelle du plafond x (nombre de jours rémunérés de la période d'emploi / nombre de jours calendaires du mois)

cf https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/la-base-de-calcul/lassiette-maximale/la-notion-de-plafond/le-calcul-du-plafond/prise-en-compte-des-absences.html

Ce qui donnerait quelque chose comme : 

Avant :
```yaml
contrat salarié . temps de travail . quotité de travail effective:
  description: >-
    Le plafond de la sécurité sociale doit être pro-ratisé en retirant les
    absences ainsi que les jours passés au chômage partiel.
  formule: temps de travail . temps effectif / (base légale * période . semaines par mois)

contrat salarié . plafond sécurité sociale:
  acronyme: PSS
  unité: €/mois
  formule:
    valeur: plafond sécurité sociale temps plein * temps de travail . quotité de travail effective
    plancher: 1 €/mois
```
Après (pseudo code) :
```yaml
contrat salarié . temps de travail . quotité de travail effective:
  formule: arrondi_entier_supérieur(contrat salarié . temps de travail . base légale / 5) / période . jours calendaires par mois

contrat salarié . plafond sécurité sociale:
  acronyme: PSS
  unité: €/mois
  formule:
    valeur: plafond sécurité sociale temps plein * temps de travail . quotité de travail effective
    plancher: 1 €/mois
```
Que pensez-vous de ce changement ? Et de son implémentation ? A ma connaissance il manquerait aujourd'hui la possibilité de faire un arrondi à l'unité supérieure.

**Comment by johangirod** [comment]
Je te remercie pour la proposition. Ceci étant dit, il y a une incompréhension : les règles de `modele-social` concernant la quotité de travail effective ne prennent pas en compte les absences non rémunérées. En effet, seules les réductions de plafond dues à une activité partielle ou un temps partiel sont implémentées.

Je ne pense pas que nous l'ajouterons prochainement dans `modele-social` car cela n'entre pas dans le domaine de la simulation (et cela obligerait à avoir des informations sur le nombre de jours calendaires par mois).

En revanche, il est tout à fait possible d'ajouter cette règle de votre côté en remplaçant la valeur du plafond de Sécurité sociale proratisé : 

**Règles modele-social**
```yaml
contrat salarié . temps de travail . quotité de travail effective:
  description: >-
    Le plafond de la sécurité sociale doit être pro-ratisé en retirant les
    absences ainsi que les jours passés au chômage partiel.
  formule: temps de travail . temps effectif / (base légale * période . semaines par mois)

contrat salarié . plafond sécurité sociale:
  acronyme: PSS
  unité: €/mois
  formule:
    valeur: plafond sécurité sociale temps plein * temps de travail . quotité de travail effective
    plancher: 1 €/mois
```
**Règles custom**
```yaml
plafond sécurité sociale avec absences:
  remplace: contrat salarié . plafond sécurité sociale
  produit: 
    assiette: contrat salarié . plafond sécurité sociale 
    taux: 
      nom: prorata absence
      valeur: (jours calendaires du mois - jours d'absences non rémunérés) / jours calendaires du mois
```

Les valeurs `jours calendaires du mois` et `jours d'absences non rémunérés` étant définie dans comme paramètres d'entrée dans la situation.

Concernant l'arrondi à l'unité supérieur, c'est effectivement une bonne idée. En attendant, il est toujours possible d'ajouter 0.4999999999  à la valeur avant l'arrondi, même si ce n'est pas idéal.
