### ISSUE TITLE
🐛 MAJ des auto entrepreneur pour 2023

### ISSUE THREAD

**Issue by wiinxt** [betagouv/mon-entreprise#2455]
### Description du problème

Les nouveau seuils serais de 188 700 euros et 77 700 euros 

pour la franchise en base de TVA:
ventes: seuil de base 91 900 € et pour seuil majoré 101 000 €
services: seuil de base 36 800 € et pour seuil majoré 39 100 €

Baisse de cotisation depuis le 1er octobre 2022 
ventes: 12,30 %
services: 21,20 %.
(je confirme le 21,20 % car j'ai fait ma déclaration avant hier et j'avais pas compris pourquoi c'était moins ^^)

source: https://solutions.lesechos.fr/juridique/c/quoi-de-neuf-pour-les-micro-entrepreneurs-en-2023-35501/
TODO: chercher un source du gouv

**Comment by wiinxt** [comment]
après les changement de https://github.com/betagouv/mon-entreprise/pull/2442 on pourra ajouter ça
```yaml
entreprise . chiffre d'affaires . seuil micro . libérale:
  unité: €/an
  variations:
    - si: date >= 01/2023
      alors: 77700 €/an
    - sinon: 72600 €/an

entreprise . chiffre d'affaires . seuil micro . total:
  unité: €/an
  variations:
    - si: date >= 01/2023
      alors: 188700 €/an
    - sinon: 176200 €/an
```
