### ISSUE TITLE
Evolution du mécanisme "composantes"

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#247]
Pour gérer plusieurs décompositions alternatives, voilà une idée d'évolution.

```
- espace: contrat salarié
  nom: CSG
  formule:
    multiplication:
      assiette: assiette CSG
      taux: 
        décomposition par:
            branche:
              maladie: 7.75%
              famille: 0.85%
              autres: 0.6%

            déductibilité:
              déductible: 2.4%
              non déductible: 6.8%
```
