### ISSUE TITLE
Mettre à jour les caisse de retraite des professions libérales

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#2864]
Les caisses de retraites CNAVPL mettent un peu de temps à publier les chiffres. A faire fin janvier / début février.

**Comment by liliced** [comment]
J'ai mis à jour les chiffres suivants :
- valeur du point et valeur d'acquisition du point de la retraite complémentaire AGIRC ARRCO
- valeur du point de la retraire de base CNAVPL
- valeur du point et valeur d'acquisition du point de la retraite complémentaire Cipav

Cela résoudra peut-être aussi https://github.com/betagouv/mon-entreprise/issues/3000

Cependant j'ai aussi trouvé 2 règles que je n'ai pas comprises.
Pour la 1ère je ne retrouve pas les taux dans le document en référence :
```
protection sociale . retraite . complémentaire . RCI:
    revenu cotisé auto-entrepreneur:
      applicable si: dirigeant . auto-entrepreneur
      remplace:
        références à:
          dirigeant . indépendant . cotisations et contributions . retraite
          complémentaire
        dans: points acquis
      somme:
        - produit:
            - entreprise . chiffre d'affaires . vente restauration hébergement
            - variations:
                - si: date >= 10/2022
                  alors: 2.03%
                - sinon: 2.04%
        - produit:
            - entreprise . chiffre d'affaires . service BIC
            - 3.50%
        - produit:
            - entreprise . chiffre d'affaires . service BIC
            - 0%
      références:
        Article D613-6 du code de la sécurité sociale: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000046714699/2022-12-10/

```

Pour la 2ème le document date de 2022 et le régime a changé plusieurs fois depuis.
```
protection sociale . retraite . trimestres . auto-entrepreneur CIPAV:
  applicable si:
    toutes ces conditions:
      - dirigeant . auto-entrepreneur
      - entreprise . activité . nature . libérale . réglementée
  remplace: retraite . trimestres
  grille:
    assiette: entreprise . chiffre d'affaires
    multiplicateur: 2421 €/an
    tranches:
      - montant: 0 trimestres validés/an
        plafond: 1
      - montant: 1 trimestres validés/an
        plafond: 2
      - montant: 2 trimestres validés/an
        plafond: 3
      - montant: 3 trimestres validés/an
        plafond: 4
      - montant: 4 trimestres validés/an
  références:
    Le régime retraite de base des auto-entrepreneur: https://www.lacipav.fr/sites/default/files/2022-01/Guide%20pratique%202022%20-%20Auto-entrepreneurs%20-%20La%20Cipav_0.pdf?page=10
```

Avant de me plonger dans de plus profondes recherches est-ce que quelqu'un saurait si elles sont toujours pertinentes ?

**Comment by liliced** [comment]
J'ai aussi trouvé 2 liens morts :
- Salaire validant un trimestre: https://www.legislation.cnav.fr/#/bareme?file_leaf_ref=salaire_validant_un_trimestre_montant_bar.aspx
- Valeur de service du point de retraite complémentaire: https://www.legislation.cnav.fr/#/bareme?file_leaf_ref=rci_valeur_point_bar.aspx

Et un lien qui n'est plus à jour (redirection vers une page qui n'est pas spécifique aux indépendants) : 
- Fonctionnement de la retraite complémentaire des indépendants': https://www.lassuranceretraite.fr/portail-info/home/actif/travailleur-independant/calcul-retraite/retraite-complementaire.html

Je le mets là car si on met à jour toutes les données liées à la retraite on aura de quoi les remplacer.

**Comment by glopezrios** [comment]
@liliced Voici déjà de premiers éléments de réponses rapides:

Concernant la 2ème règle citée (seuils de chiffres d'affaires pour validation de trimestre d'un auto-entrepreneur relevant de la CIPAV), cette règle me semble toujours d'actualité. Par contre, le multiplicateur a évolué. Il était de 2421 €/an en 2022. Il est passé à 2 571 €/ an en 2023 (chiffre trouvé sur: https://entreprendre.service-public.fr/vosdroits/F23369). Par contre, je n'arrive pas à trouver le multiplicateur pour 2024: j'ai cherché sur le site de la CIPAV (et notamment sur leurs guides pratiques) mais je n'ai pas réussi à trouver des infos concernant les micro-entrepreneurs plus récentes que 2022 (je n'ai peut-être pas cherché au bon endroit?). 

A noter que pour les autres activités (dont les professions libérales non CIPAV), le calcul du nombre de trimestres validés ne se fait pas directement en fonction du chiffre d'affaires, mais en fonction du montant cotisé (qui dépend lui-même de la nature de l'activité) et du montant du SMIC horaire. 

Concernant la 1ère règle citée (calcul du nombre de points acquis pour la retraite complémentaire des auto-entrepreneurs?), je suppose que les taux concernent [le "revenu cotisé entrepreneur"](https://mon-entreprise.urssaf.fr/documentation/protection-sociale/retraite/compl%C3%A9mentaire/RCI/revenu-cotis%C3%A9-auto%E2%80%91entrepreneur). Ces taux (par exemple 2,03% pour les activités de commerce/vente) sont calculés en multipliant le taux global de cotisations (par exemple 12,3% pour la vente) par la part des cotisations affectées à la retraite complémentaire (par exemple 16,5% pour la vente). Ils permettent de calculer le montant cotisé, directement à partir du chiffre d'affaires.

Plus de détails sur la répartition des cotisations des micro-entrepreneurs (cf. notamment page 9): https://legislation.lassuranceretraite.fr/Pdf/circulaire_cnav_2024_23_16072024.pdf

Le calcul du nombre de points acquis dépend du montant cotisé pour la retraite complémentaire, qui dépend lui-même de la répartition du montant global des cotisations, d'où la mention à l'article D613-6 du code de la sécurité sociale.

Je laisserai @JalilArfaoui et @VeroniqueR75 qui ont travaillé sur cette problématique des droits retraire pour les auto-entrepreneurs.

**Comment by liliced** [comment]
Merci @glopezrios pour ta réponse claire, complète et documentée ! :pray: 
J'ai pu mettre à jour la règle `protection sociale . retraite . trimestres . auto-entrepreneur CIPAV` avec le montant 2023 en attendant celui de 2024.

Ce sera sûrement @JalilArfaoui qui pourra me répondre mais où la règle `protection sociale . retraite . complémentaire . RCI` est-elle vraiment utilisée ?
Il y a dans `auto-entrepreneur.publicodes` les taux de répartition des cotisations, et c'est ça qui est utilisé sur le simulateur "auto-entrepreneur" par exemple : 
  ```
dirigeant . auto-entrepreneur . cotisations et contributions . cotisations:
    service BNC:
      description: Cotisations pour la part du chiffre d'affaires en prestation de service BNC
      produit:
        - entreprise . chiffre d'affaires . service BNC
        - taux
      unité: €/mois

      avec:
        taux:
          variations:
            - si: date >= 07/2024
              alors: 23.1%
            - si: date >= 10/2022
              alors: 21.1%
            - sinon: 22%

        répartition:
          avec:
            maladie-maternité:
              valeur: service BNC * taux de répartition
              avec:
                taux de répartition: 3.90%
            invalidité-décès:
              valeur: service BNC * taux de répartition
              avec:
                taux de répartition: 4.10%
            retraite de base:
              valeur: service BNC * taux de répartition
              avec:
                taux de répartition: 55.50%
            retraite complémentaire:
              valeur: service BNC * taux de répartition
              avec:
                taux de répartition: 0%
            autres contributions:
              valeur: service BNC * taux de répartition
              avec:
                taux de répartition: 36.50%
```
Cette mise en forme me semble mieux car c'est la même que celle de l'Urssaf ou de l'Assurance retraite. Et comme ça on retrouve directement les chiffres des références dans les règles. C'est plus compréhensible et plus facile à vérifier et mettre à jour.
J'aimerais bien supprimer l'autre règle si possible.
