### ISSUE TITLE
[artiste-auteur] Remplacer le seuil d'affiliation RAAP par un multiple du SMIC

### ISSUE THREAD

**Issue by liliced** [betagouv/mon-entreprise#3272]
Actuellement on a la règle suivante : 
```
artiste-auteur . cotisations . IRCEC . cotisation RAAP . seuil d'affiliation:
  valeur:
    variations:
      - si: date >= 01/2024
        alors: 10143 €/an
      - sinon: 9135 €/an
```
Les valeurs sont en dur alors qu'elles correspondent en réalité à **900 x le SMIC horaire au 1er janvier de l'année précédente**.
Par exemple en 2023, `9135 = 900 x 10.57` et en 2024 `10143 = 900 x 11.27` .
