### ISSUE TITLE
Harmoniser le traitement des attributs des variables

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#33]
Faire disparaître le statut particulier des attributs "formule" et "non applicable" (des "ruleProp") d'une variable, par rapport au traitement des autres attributs sous forme de mécanismes. Cette exception introduit beaucoup de code inutile dans traverse et à d'autres endroits, et de la confusion. 

@Morendil J'aimerais transformer `non applicable si` en mécanisme applicable aussi dans le corps de la formule. Son comportement serait de court-circuiter et annuler les mécanismes de même niveau que lui. 
Ex.
 
```yaml
formule: 
  non applicable si: age < 18
  multiplication: 
    taux: 6%
    assiette: salaire
```

Comme tu le suggérais, ce serait bien d'introduire une étape de réécriture de l'arbre, préliminaire à `treat()`, pour ici obtenir : 

  ```yaml
formule: 
  non applicable si: 
    condition: age < 18
    sinon: 
      multiplication: 
        taux: 6%
        assiette: salaire
```

On peut alors imaginer réécrire certains mécanismes en des opérations élémentaires, eg. `barème`...
