### ISSUE TITLE
Bug when a private rule is disactivated by its parent

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#3359]
In the following situation : 
```
a: 
  valeur: non
  avec:

    a:
      privé: oui
      valeur:  oui
      remplace: b

b: 12
x: b
```

The replacement defined in `a . a` is always applicable, even if `a` is `non`. This is because `a . a` is applicable, it shouldn't be.
