### ISSUE TITLE
Règles d'arrondis des cotisations

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#490]
> Problème pertinent pour #481 

# Pour les indépendants

Supprimer dans les calculs les chiffres après la virgule.

Les règles d’arrondi sont :
- L’assiette sociale annuelle est toujours arrondie.
- L’arrondi des cotisations est effectué sur la cotisation annuelle de chaque risque.
- L’arrondi des cotisations est effectué à l’euro le plus proche, la fraction 0,5 comptant pour 1.
- Les cotisations sont arrondies risque par risque

**Comment by mquandalle** [comment]
Est-ce qu'on pourrait ajouter un mécanisme `arrondi` pour traiter ces cas ?

```yaml
- espace: indépendant
  nom: cotisations et contributions
  formule:
    arrondi: 
      somme:
        - cotisations à payer
        - CSG et CRDS
        - formation professionnelle
```
