### ISSUE TITLE
Ajouter un mécanisme "plafonnement"

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#642]
Ce mécanisme est utilisé seulement 7 fois dans toute la base de règle, et à chaque fois pour définir des plafonnements. L'affichage de ce mécanisme dans les pages de documentation porte à confusion et il serait préférable d'afficher systématiquement une notion de "plafond" plutôt que de "minimum" — qui est plus un détail d'implémentation du plafonnement.

L'attribut "plafond" du mécanisme `multiplication` est utilisé 19 fois, donc la transition vers la notion de plafond est bien entamée. Il serait bien d'uniformiser les règles qui ne sont pas encore converties. 
**edit:** en fait le plafonnement d'une `multiplication` s'applique seulement sur son assiette, il n'est donc pas possible de remplacer "le minimum de" par l'attribut "plafond" de `multiplication`

Il me semble néanmoins que l'on ne peut pas encore utiliser d'attribut "plafond" pour les `somme`s :

```yaml
le minimum de:
  - somme:
      - trimestres salarié
      - trimestres indépendant
      - trimestres auto entrepreneur
  - 4
```

Actuellement c'est parfois le mécanisme `multiplication` qui est détourné pour pouvoir définir le plafonnement d'une somme, par exemple :

```yaml
multiplication:
  assiette: taux RSA part variable + 1.35%
  plafond: 6.35%
```

Idée: remplacer "le minimum de" par un mécanisme "plafonnement" qui fait pareil mais avec un meilleur affichage dans les pages de documentation

**Comment by johangirod** [comment]
Tout à fait d'accord. C'est quelque chose qui m'a traversé l'esprit quand j'ai codé les heures sup. Ce serait beaucoup plus clair avec la notion de plafond. Mais j'ai un peu bloqué sur la syntaxe. Celle idéale serait un mécanisme qui arriverait au même niveau que la valeur à plafonner : 

```yaml
formule: 
  somme:
      - trimestres salarié
      - trimestres indépendant
      - trimestres auto entrepreneur
  plafonné à: 4
```
Mais cela implique de reprendre pas mal de choses dans le moteur, puisque par défaut, il n'y a qu'un mécanisme par feuille.

L'autre solution plus immédiate est effectivement l'ajout d'un nouveau mécanisme plafonnement: 
```yaml
formule: 
  plafonnement:
     assiette: 
        somme:
          - trimestres salarié
          - trimestres indépendant
          - trimestres auto entrepreneur
    plafond: 4
```
Ce qui complexifie tout de même pas mal l'écriture. Ceci dit, c'est la plus facile à mettre en oeuvre, et sans doute la plus claire.
