### ISSUE TITLE
Possibilité de definir l'unité d'une valeur litérale dans une formule

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#730]
Il n'est actuellement pas possible de définir l'unité d'une valeur littérale dans une formule, ce qui casse l'inférence :

![image](https://user-images.githubusercontent.com/1730702/66713394-b6e20600-edaa-11e9-9791-8df7f36c665e.png)

La formule correspondante :

```yaml
contrat salarié . cotisations . patronales . réductions de cotisations . déduction heures supplémentaires:
  unité: €
  formule:
    multiplication:
      assiette: temps de travail . heures supplémentaires
      facteur: 1.50
```

Il faudrait pouvoir définir `facteur: 1.50 €/heure`
