### ISSUE TITLE
Pouvoir nommer un attribut de mécanisme

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#799]
On observe une tendance naturelle à décomposer des règles complexes avec de nombreux mécanismes imbriqués en règles plus simples, et regroupées par espace de nom. Cette organisation nous permet notamment de nommer et d'avoir accès à des données inaccessibles de l’extérieur auparavant, tel que le taux d'une cotisation, une assiette ou un plafond.

On se retrouve ainsi de plus en plus avec des définitions ressemblant à ça :

```yaml
cotisation:
  formule:
    multiplication:
      assiette: assiette
      taux: taux
      plafond: plafond

cotisation . assiette:
  [...]

cotisation . taux:
  [...]

cotisation . plafond:
  [...]
```

Ici la définition de la cotisation apporte peu d'informations, mis à part la nature du mécanisme (ici un produit). Les arguments du mécanisme sont tous précisés dans des sous-règles de l'espace de nom, et par suite les lignes suivantes n'apportent pas d'information :

```
      assiette: assiette
      taux: taux
      plafond: plafond
```

Je ne sais pas quel serait l'alternative nous épargnant l'écriture de ces lignes redondantes. Je vois au moins deux possibilités :

* Soit conserver la décomposition en règles indépendantes, et considérer que les arguments des mécanismes prennent par défaut la valeur de la règle éponyme dans l'espace de nom :

  ```yaml
  cotisation:
    formule: multiplication

  cotisation . assiette:
    [...]

  cotisation . taux:
    [...]

  cotisation . plafond:
    [...]
  ```

* Soit supprimer les sous règles et revenir à un modèle en définition imbriquées, mais avoir un moyen d'accéder et modifier les sous nœuds d'une définition (taux, assiette, plafond) même si ce ne sont pas des règles indépendantes

J'ouvre l'issue pour suivre la réflexion, mais je ne vois aucune urgence à sortir du modèle actuel tant que l'on a pas de meilleure alternative.

**Comment by laem** [comment]
On peut aussi comme étape intermédiaire nous inspirer du JS

```js
let cat = 'Miaow';
let dog = 'Woof';
let bird = 'Peet peet';

let someObject = {
  cat,
  dog,
  bird
}
```

**Comment by mquandalle** [comment]
Le problème à mon avis, que ça soit avec la version JS `{ assiette, taux, plafond }` ou avec ma proposition de considérer que ce sont des valeurs par défaut, c'est que l'écriture des règles s'éloigne de la manière dont elle sont définies dans la loi (et qu'en plus on s'éloigne de cette manière d'écrire essentiellement pour des raisons techniques, à savoir pouvoir référencer et modifier un taux ou une assiette).

Probablement faudrait-il plutôt revenir vers la manière précédente en indiquant directement le taux dans l'argument taux `taux: 3.5%` et ensuite pouvoir le référencer et le modifier avec `règle . taux` sans avoir besoin de créer une règle distincte.

**Comment by laem** [comment]
Oui super idée.

**Comment by mquandalle** [comment]
Je poursuis sur l'idée qu'il faudrait re-définir dans un même bloc les paramètres principaux d'une règle (taux, assiette, plafond, etc.) plutôt que de les séparer dans des règles enfants comme nous avons été amenés à le faire pour traiter des cas particuliers (conventions collectives qui modifient un taux, option de surcotisation qui change l'assiette, etc.)

Avant d’atterrir sur le modèle actuel du mécanisme `remplace` nous avions considéré la possibilité de profiter de l'arbre Yaml et d'utiliser une notion de chemin. `remplace: salarié . cotisation vieillesse . multiplication . taux` qui s'est toutefois révélée trop fragile :

* Difficulté de lecture et d'écriture des chemins
* Certaines valeurs sont difficilement accessibles, par exemple un taux situé dans un barème `cotisation . barème . tranches . 3 . taux`
* Fragilité en cas de ré-organisation, une règle qui utilise un chemin dépend d'une implémentation très spécifique (qui est cassée si on change une somme en `composantes` ou que l'on englobe un résultat dans un `encadrement`) ce qui n'est pas du tout visible au niveau de la règle, avec pour conséquence un risque qu'une modification bénigne localement casse du code très éloigné sans un indice qui le laissait penser
* Amendement dans plusieurs règles à la fois nécessite l'écriture de plusieurs chemins

Bref le modèle choisi, de substitution basée sur les noms est bien plus robuste. Pour le conserver tout en regroupant les attributs `taux`, `assiette` dans une même règle il faudra donc pouvoir nommer un attribut “inline”. Au niveau de la règle cela est utile car le fait qu'un paramètre soit explicitement nommé signifie qu'il peut être référencé et modifié dans d'autres parties du code, et qu'il faut y veiller en cas de ré-organisation.

En résumé pour avoir un code publicode qui soit à la fois robuste et proche des conventions législatives il faut :
* définir les valeurs des taux, assiettes, etc. dans la règle principale et non dans des règles enfants
* ajouter une annotation `nom` à tous les endroits où une valeur peut être référencée et modifiée

Reste à voir comment implémenter ces principes dans le cadre des contraintes de la syntaxe Yaml. Une possibilité serait d'utiliser un objet `{nom, valeur}` :

```yaml
cotisation maladie:
  formule:
    multiplication:
      assiette:
        nom: assiette maladie
        valeur: assiette des cotisations
      taux:
        nom: taux maladie
        valeur: 12%

cotisation maladie . taux réduit:
  applicable si: rémunération brute < 2.5 * SMIC
  remplace: taux maladie
  formule: 7%
```

(éventuellement en ajoutant un nom de mécanisme type `règle:` au dessus des objets `{nom, valeur}`)

Cela fonctionne mais ça n'est pas idéal. Déjà en utilisant l'attribut `nom` on perd de la cohérence par rapport aux règles de premier niveau (que l'on nomme sans utiliser d'attribut `nom`), et cela nous oblige à utiliser un attribut `valeur` dont on se passerait volontiers. Une autre idée pourrait être de définir le nom de la sous règle dans une clé d'un objet JSON et sa valeur comme valeur de l'objet, par symétrie avec les règles de premier niveau :

```yaml
cotisation maladie:
  formule:
    multiplication:
      assiette:
        assiette maladie: assiette des cotisations
      taux:
        taux maladie: 12%
```

Mais ça n'est facile à comprendre.

Il y a d'autres syntaxes possibles, je vais continuer à y réfléchir mais je souhaitais partager la réflexion.

**Comment by johangirod** [comment]
J'avais pensé au nommage directement dans la valeur : 
```
cotisation maladie:
  formule:
    multiplication:
      assiette: assiette des cotisations (~ assiette maladie) 
      taux: 12% (~ taux)
```
L'avantage est de pouvoir nommer des partie d'expressions ou de somme

**Comment by laem** [comment]
@johan en mettant ```yaml tu as une colorisation syntaxique personnalisée dans les blocs de code markdown

**Comment by mquandalle** [comment]
J'ai l'impression que dans 80% des cas, on veut utiliser le nom "standard" de l'argument dans son espace de nom, plutôt qu'un nom personnalisé, ie utiliser `cotisation maladie . assiette` plutôt que `cotisation maladie . assiette maladie`.

Peut-être qu'on pourrait introduire une nouvelle syntaxe, comme tu le proposes @johangirod, mais au niveau de la clé Yaml plutôt que de la valeur :

```yaml
cotisation maladie:
  formule:
    multiplication:
      [assiette]: assiette des cotisations
      [taux]: 12%
```

et si l'on veut donner un nom non standard :

```yaml
cotisation maladie:
  formule:
    multiplication:
      [assiette = assiette maladie]: assiette des cotisations
      [taux]: 12%
```
