### ISSUE TITLE
Fusionner les attributs "formule" et "par défaut"

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#836]
Dans le cadre de la discussion #796 sur la formalisation de Publicode, j'ai décrit un modèle de graphe orienté dans lequel chaque règle est un nœud (et où les arcs sont les dépendances). On donne une situation en entrée en forçant la valeur de certains nœuds, puis on calcule des "objectifs" en suivant les arcs du graphe.

Le calcul de la valeur d'un nœud se fait en évaluant sa `formule`, s'il n'y a pas de formule on va utiliser la valeur `par défaut`. Dans la mesure où l'on peut forcer la valeur de n'importe quel nœud dans la situation en entrée, l'attribut `formule` correspond déjà à une valeur par défaut (par exemple [ici](https://github.com/betagouv/mon-entreprise/blob/813b79e9615142ab9f476eec8173c5d058afff07/source/r%C3%A8gles/base.yaml#L84)) et il n'y a donc pas de différence sémantique entre une `formule` et une valeur `par défaut`. Il est donc possible de fusionner ces deux attributs.

La gestion du remplissage progressif du formulaire (et la distinction entre les valeurs par défaut et les réponses de l'utilisateur) peut se faire exclusivement au niveau du simulateur (c'est déjà largement le cas aujourd'hui), qui peut collecter l'ensemble des "questions", éventuellement les ré-ordonner et en supprimer certaines (liste noire) et forcer certaines valeurs dans la situation. Ensuite pour toutes les questions qui n'ont pas encore de réponse, on sait que la valeur fournie par le moteur correspond à la valeur par défaut, sans qu'il y ait besoin que le moteur en lui-même face la distinction entre les valeurs provenant d'une `formule` et celles venant de l'attribut `par défaut`.

Je pense que cela simplifierait un peu le modèle du moteur, et dans le code permettrait de supprimer des abstractions comme `situationsWithDefaultsSelector`.

La modification devrait être assez facile à faire, mais elle impose un second changement. En effet pour les unions disjointes on utilise l'attribut `formule` non pas pour calculer la valeur du nœud mais pour donner la liste des valeurs possibles :

```yaml
contrat salarié:
  icônes: 📄
  question: De quel type de contrat s'agit-il ?
  formule:
    une possibilité:
      choix obligatoire: oui
      possibilités:
        - CDI
        - CDD
        - apprentissage
        - stage
  par défaut: CDI
```

Ici la formule ne sert pas à calculer la valeur de la règle `contrat salarié` à partir d'autres dépendances, mais à donner la liste des valeurs possibles. Il me semble que c'est un usage bien distinct qui ne devrait pas se trouver dans `formule`. Si on sort la liste des possibilités de l'attribut `formule` on peut alors l'utiliser pour spécifier la valeur par défaut comme proposé ci-dessus.

Il faut alors un nouvel attribut de premier niveau pour spécifier la liste des valeurs possible (le type) d'un noeud. Actuellement l'attribut `unité` permet cette gestion de type mais seulement pour les valeurs numériques, on peut donc imaginer un autre attribut au même niveau que `unité` mais pour les unions disjointes :

```yaml
contrat salarié:
  icônes: 📄
  question: De quel type de contrat s'agit-il ?
  formule: CDI
  possibilités:
    - CDI
    - CDD
    - apprentissage
    - stage
```

Peut-être que l'utilisation de `formule: CDI` est moins claire sur l'intention que `par défaut: CDI` et que l'on pourrait garder cette écriture comme alternative, qui au niveau de l'implémentation aurait exactement le même comportement que `formule`.

L'objectif de cette modification est d'avoir un modèle d’exécution plus clair : 
* L'attribut `formule` sert à calculer la valeur d'un nœud
* Dans la "situation" en entrée on peut forcer la valeur de n'importe quel nœud, et l'attribut `formule` correspond alors à une valeur par défaut

Intuitivement cette modification devrait simplifier un peu le code à plusieurs endroits, mais ça reste évidemment à vérifier avec son implémentation.

**Comment by mquandalle** [comment]
Par ailleurs même si on garde le terme `par défaut`, le fait de fusionner le code avec `formule` permettra de gérer l'inférence d'unité pour les valeurs par défaut comme pour les formules, c'est à dire remplacer

```yaml
contrat salarié . rémunération . primes . activité . base:
  titre: primes d'activité
  unité: €/mois
  question: Quel est le montant des primes liées à l'activité du salarié ?
  par défaut: 0
```

par

```yaml
contrat salarié . rémunération . primes . activité . base:
  titre: primes d'activité
  question: Quel est le montant des primes liées à l'activité du salarié ?
  par défaut: 0 €/mois
```

**Comment by laem** [comment]
Super idée ! 
Par contre, j'ai toujours trouvé que le `formule: [nombre]` faisait bizarre à la lecture. Idem donc pour le `formule: [chaine de charactères]`, le `par défaut` est bien plus explicite.

**Comment by mquandalle** [comment]
Sinon on peut aussi utiliser un terme plus neutre comme `valeur` qui éviterait d'avoir deux noms (`formule` et `par défaut`) pour le même attribut.

**Comment by johangirod** [comment]
Super idée, c'est effectivement quelque chose qui m'avait déjà traversé l'esprit, et c'est vrai que la gestion de l'attribut "par défaut" ajoute une dose de complexité dont on se passerait bien. 

Je suis en tout point d'accord avec les conclusions retenues. 

Concernant le choix du vocabulaire, je pense qu'il est utile de garder la notion du `par défaut`.
- Le contrat salarié par défaut est un CDI
- Le nombre d'heure travaillées est par défaut 35h/semaine
- Un CDD est par défaut un CDD d'usage

Par ailleurs, l'ajout de l'information par défaut nous informe qu'il s'agit d'une feuille de l'arbre de calcul qui est paramétrable. Ce qui est nécessaire pour le recensement des missingVariables. Perdre cette distinction nous oblige à vérifier que la valeur renseignée est bien celle d'une constante, et qu'il existe une question associée au noeud : plus complexe, plus "magique".

**Comment by mquandalle** [comment]
Concernant la collecte des variables manquantes, je me disais que filtrer les règles pour lequel il y a un attribut `question` était équivalent (aujourd'hui on met soit `question` + `par défaut`, soit `formule`, l'information concernant l'existence d'une valeur par défaut existe déjà dans le fait que la règle possède une question).

**Comment by johangirod** [comment]
Effectivement. Après reflexion, je suis plutôt pour la suppression de `par défaut`. Cela permet de formaliser les entrée utilisateur comme le mécanisme de remplacement de valeur, et cela diminue la surface de notre api.

**Comment by mquandalle** [comment]
Ah oui intéressant le parallèle entre un remplacement de valeur (dans la base de règle) et une simulation qui force des valeurs et peut donc utiliser la même logique de remplacement.

**Comment by laem** [comment]
Je fais la même réflexion qu'[ici](https://github.com/betagouv/mon-entreprise/pull/824#issuecomment-571202131) : je trouve le mot clef "valeur" trop vague.

Je pense notamment au monde des tableurs, où "formule" désigne une case qui sera calculée, contrairement à une case contenant une constante. D'ailleurs @mquandalle on y retrouve ta proposition de `=` pour déclencher l'écriture d'une formule.

Je suis assez convaincu qu'on peut comprendre sans lire une documentation ce bout de code 

```yaml

brut:
  question: Quel est votre revenu brut ?
  par défaut: 30 000 €

net: 
  formule: brut * 2%
```

Alors qu'ici, j'aurai la crainte que `valeur: 30 000€` écrase la question. 

Et pour `net`, je trouve que valeur est trompeur : ça désigne à mon avis plutôt la valeur courante qu'on appelle "nodeValue" après calcul de la variable `net`plutôt que l'algorithme qui mène à cette valeur courante. 
Je trouve qu'on perd la signification "la formule est la suivante: brut * 2%".

```yaml

brut:
  question: Quel est votre revenu brut ?
  valeur: 30 000 €

net: 
  valeur: brut * 2%
```
