### ISSUE TITLE
Le mécanisme variation force le type d'unité retour à '%' lorsqu'aucune unité n'est spécifiée

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#997]
```yaml
value: 
  formule: 
    variations: 
      - si: 10 > 1
        alors: 3
      - sinon: 5
```
=> 300% ([Voir sur le studio](https://publi.codes/studio?code=%0Avalue%3A%20%0A%20%20formule%3A%20%0A%20%20%20%20variations%3A%20%0A%20%20%20%20%20%20-%20si%3A%2010%20%3E%201%0A%20%20%20%20%20%20%20%20alors%3A%203%0A%20%20%20%20%20%20-%20sinon%3A%205))

On attendait 3 comme résultat.
